---
- name: create users on localhost
  hosts: localhost
  become: true
  vars_files:
    - users_list.yml
  tasks:
  - name: creating users as required
    vars:
      password: "{{ lookup('password', './password-{{ item.name }} length=6') }}"
    user:
      name: "{{ item.name }}"
      uid: "{{ item.uid }}"
      comment: "{{ item.first | capitalize }} {{ item.middle | capitalize }} {{ item.last | capitalize }}"
      password: "{{ password | password_hash('sha512') }}"
      update_password: on_create
    with_items: "{{ myusers }}"
