---
- name: creating users and passwords
  hosts: localhost
  gather_facts: no
  become: true
  become_user: root
  vars_files:
    - users.yml
  tasks:
  - name: creating users with password as required
    vars:
      password: "{{ lookup('password', './password-{{ item.name }}' ' length=6') }}"
    user:
      name: "{{ item.name }}"
      uid:  "{{ item.uid }}"
      comment: "{{ item.first | capitalize }} {{ item.middle | capitalize }} {{ item.last | capitalize }}"
      password: "{{ password | password_hash('sha512') }}"
      update_password: on_create
    with_items:
      - "{{ myusers }}"
